// angular-form-builder/projects/angular-form-builder-lib/src/lib/form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
    selector: 'lib-form[specification]',
    templateUrl: './form.component.html',
    styleUrls: ['./form.component.scss']
})
export class FormComponent<Spec extends Object> {

    @Input() specification: Spec = null!; // Angular guarantees that item will have a value when the component is initialized because of the @Input decorator.
    @Output() specificationChange: EventEmitter<Spec> = new EventEmitter<Spec>();
    
    @Output() onSubmit: EventEmitter<Spec> = new EventEmitter<Spec>();

    /**
     * This is the callback for the submit button of the form.
     * It emits the current specification to whatever parent component 
     * is using this form component.
     * @param event 
     */
    onSubmitClicked(event: Event){
        event.preventDefault();
        this.onSubmit.emit(this.specification);
    }
}

<form>
    <lib-form-item [(item)]="specification"></lib-form-item>
    <input type="submit" (click)="onSubmitClicked($event)" value="Submit">
</form>

// react-form-builder/src/form/form.tsx
import React, { useState } from "react";
import './form.scss';
import { deepCopy } from "typesafe-form-builder";
import { FormItem } from "./form-item";

type FormProps<Spec extends Object> = {
    specification: Spec,
    onSpecificationChange: <R>(newSpecification: Spec) => R | void,
    onSubmit: <R>(newSpecification: Spec) => R | void
}

export function Form <Spec extends Object>(props: FormProps<Spec>) {

    /**
     * Specification state is created from the specification given through
     * this component's props.
     */
    const [specification, setSpecification] = useState(props.specification);

    /**
     * Called when the data in the specification is modified.
     * @param newSpecification new specification object with updated data.
     */
    const onSpecificationChange = (newSpecification: Spec) => {
        const specificationCopy = {...newSpecification};
        props.onSpecificationChange(specificationCopy);
        setSpecification(specificationCopy);
    }

    /**
     * This is the callback for the submit button of the form.
     * It gives the current specification to whatever parent component 
     * is using this form component.
     * @param event 
     */
    const onSubmitClicked = (event: React.FormEvent) => {
        event.preventDefault();
        props.onSubmit(deepCopy({...specification}));
    }
    
    return <form>
        <FormItem item={specification} onItemChange={onSpecificationChange} />
        <input type="submit" onClick={onSubmitClicked} value="Submit"></input>
    </form>
}
