// angular-form-builder/projects/angular-form-builder-lib/src/lib/form-item/form-item.component.ts
import { KeyValue } from '@angular/common';
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { customTypeOf, PrimitiveTypes, isPrimitive } from 'typesafe-form-builder';

@Component({
    selector: 'lib-form-item[item]',
    templateUrl: './form-item.component.html',
    styleUrls: ['./form-item.component.scss']
})
export class FormItemComponent<Item extends PrimitiveTypes | Object> {

    @Input() item: Item = null!; // Angular guarantees that item will have a value when the component is initialized because of the @Input decorator.
    @Output() itemChange: EventEmitter<Item> = new EventEmitter<Item>();

    /**
     * If `item` contains a primitive value, this callback will be called when
     * it changes.
     * The parent element will then be notified through the event emitter.
     * @param newItem new value for item.
     */
    onItemChange(newItem: Item) {
        this.item = newItem;
        this.itemChange.emit(newItem);
    }

    /**
     * If `item` is an object, this callback will be called when the value of
     * one of its properties changes.
     * @param prop the key of the property that changed.
     * @param value the new value belonging to that property.
     */
    onItemPropChange(prop: keyof Item, value: Item[typeof prop]) {
        this.item[prop] = value;
    }

    /**
     * Used when rendering object keys with an ngFor loop.
     * If this is not used the input field loses focus everytime
     * a character is entered by the user.
     * source: https://stackoverflow.com/a/46565538
     */
    propTrackByFn<K, V>(index: number, keyVal: KeyValue<K, V>) {
        return index;
    }

    /**
     * isPrimitive function as property of this component so it can be used
     * in the Angular template.
     *
     * @memberof FormItemComponent
     */
    isPrimitive = isPrimitive;

    /**
     * customTypeOf function as property of this component so it can be used
     * in the Angular template.
     *
     * @memberof FormItemComponent
     */
    customTypeOf = customTypeOf;

    /**
     * Wrapper of customTypeOf function for checking the type of array.
     * Added as property so it can be used in the Angular template.
     * @param val value that will be checked whether it's an array.
     * @returns true if val is an array, otherwise false.
     */
    isArray = <ArrEllement extends Item>(val: any): val is Array<ArrEllement> => customTypeOf(val, "array");

}

<!-- item is a primitive value -->
<span *ngIf="isPrimitive(item); else arrayBlock">
    <lib-form-primitive-input [value]="item" (valueChange)="onItemChange($event)"></lib-form-primitive-input>
</span>

<!-- item is an array -->
<ng-template #arrayBlock>
    <ng-container *ngIf="isArray(item); else objectBlock">
        <br/>
        <ul>
            <li *ngFor="let arrayItem of item; let i = index">
                <span *ngIf="item.length > 1" class="num">{{i+1}}</span>
                <lib-form-item [item]="arrayItem"></lib-form-item>
            </li>
        </ul>
    </ng-container>
</ng-template>

<!-- item is a child object -->
<ng-template #objectBlock>
    <div *ngIf="customTypeOf(item, 'object')" class="object">
        <div *ngFor="let keyVal of item | objectKeyValue; trackBy: propTrackByFn" class="keyValue">
            <label>{{keyVal.key}}</label>
            <lib-form-item [item]="keyVal.value" (itemChange)="onItemPropChange(keyVal.key, $event)"></lib-form-item>
        </div>
    </div>
</ng-template>

// react-form-builder/src/form/form-item.tsx
import { useState } from "react";
import './form-item.scss';
import { deepCopy, getKeys, isPrimitive, PrimitiveTypes } from "typesafe-form-builder";
import { FormPrimitiveInput } from "./form-primitive-input";

type FormItemProps<Item extends PrimitiveTypes | Object> = {
    item: Item,
    onItemChange: <R>(item: Item) => R | void
}

export function FormItem <Item extends PrimitiveTypes | Object>(props: FormItemProps<Item>) {

    /**
     * An item can be any nested object or primitive property in the
     * specification object.
     */
    const [item, setItem] = useState(props.item);

    /**
     * Called when the item is modified.
     * Updates the state and executes callback with new value.
     * @param newItem 
     */
    const onItemChange = (newItem: Item) => {
        props.onItemChange(newItem);
        setItem(newItem);
    }

    /**
     * Called when item is an object, and one of its properties is modified.
     * @param itemObj the current item.
     * @param prop the prop whose value was modified.
     * @param value the new value of the given property.
     */
    const onItemPropChange = <ItemObj extends Object & Item>(itemObj: ItemObj, prop: keyof ItemObj, value: ItemObj[typeof prop]) => {
        const newItemObj = deepCopy(itemObj);
        newItemObj[prop] = value;
        onItemChange(newItemObj);
    }

    /**
     * Called when item is an array, and one of its elements is modified.
     * @param itemArr the current item.
     * @param index index of the element that was changed.
     * @param value new value for the given index.
     */
    const onArrayElementChange = <Element, ItemArr extends Array<Element> & Item>(itemArr: ItemArr, index: number, value: Element) => {
        const newItemArr = deepCopy(itemArr);
        newItemArr[index] = value;
        onItemChange(newItemArr);
    }

    if (isPrimitive(item))
        return <FormPrimitiveInput value={item} onValueChange={onItemChange} />
    else if (item instanceof Array)
        return <>
        <br/>
        <ul className="array">
            {item.map((arrayItem, i) => <li key={i}>
                {item.length > 1 ? <span className="num">{i+1}</span> : null}
                <FormItem item={arrayItem} onItemChange={newArrayItem => onArrayElementChange(item, i, newArrayItem)} />
            </li>)}
        </ul>
        </>
    else if (item instanceof Object)
        return <div className="object">
            {getKeys(item).map(key => 
            <div key={String(key)} className="keyValue">
                <label>{key}</label>
                <FormItem item={item[key]} onItemChange={(newItem) => onItemPropChange(item, key, newItem)}/>
            </div>)}
        </div>
    return <span>Form Item</span>
}
